Repository OpenFeign/feign, pull requests merged in 2018-09, with the labels that each got.

#789 The @Headers does not work
  core/src/main/java/feign/Contract.java
  core/src/test/java/feign/DefaultContractTest.java
Labels: waiting for feedback

#792 Return null (empty target object) if status code is 204
  jaxb/src/main/java/feign/jaxb/JAXBDecoder.java
Labels: bug

#762 Allow JAXB context caching in factory Fixes #761
  jaxb/src/main/java/feign/jaxb/JAXBContextFactory.java
  jaxb/src/test/java/feign/jaxb/JAXBContextFactoryTest.java
Labels: enhancement, ready to merge

#799 fix #797 fix #798: JAXRSContract sets a single Content-Type value
  core/src/main/java/feign/RequestTemplate.java
  core/src/test/java/feign/assertj/RequestTemplateAssert.java
  jaxrs/README.md
  jaxrs/src/main/java/feign/jaxrs/JAXRSContract.java
  jaxrs/src/test/java/feign/jaxrs/JAXRSContractTest.java
  jaxrs2/README.md
Labels: enhancement, waiting for feedback, waiting for votes
