Repository OpenFeign/feign, pull requests merged in 2018-10, with the labels that each got.

#804 Enforce format
  core/src/test/java/feign/DefaultContractTest.java
  example-github/src/main/java/feign/example/github/GitHubExample.java
  example-wikipedia/src/main/java/feign/example/wikipedia/ResponseAdapter.java
  example-wikipedia/src/main/java/feign/example/wikipedia/WikipediaExample.java
  jaxb/src/main/java/feign/jaxb/JAXBContextFactory.java
  jaxrs/src/main/java/feign/jaxrs/JAXRSContract.java
  jaxrs/src/test/java/feign/jaxrs/JAXRSContractTest.java
  pom.xml
  travis/publish.sh
Labels: hacktoberfest

#802 add BeanQueryMapEncoder
  README.md
  core/src/main/java/feign/QueryMapEncoder.java
  core/src/main/java/feign/querymap/BeanQueryMapEncoder.java
  core/src/main/java/feign/querymap/FieldQueryMapEncoder.java
  core/src/test/java/feign/DefaultQueryMapEncoderTest.java
  core/src/test/java/feign/FeignTest.java
  core/src/test/java/feign/PropertyPojo.java
  core/src/test/java/feign/querymap/PropertyQueryMapEncoderTest.java
Labels: enhancement, ready to merge

#807 Make jaxb modules build on java 11
  .travis.yml
  jackson-jaxb/pom.xml
  jaxb/pom.xml
  pom.xml
Labels: hacktoberfest

#806 Introduced java 11 module with http2 client
  README.md
  java11/README.md
  java11/pom.xml
  java11/src/main/java/feign/httpclient/Http2Client.java
  java11/src/test/java/feign/httpclient/test/Http2ClientTest.java
  pom.xml
Labels: hacktoberfest

#814 Sorted all poms and include sortpom to enforce pom layout
  example-github/pom.xml
  example-wikipedia/pom.xml
  gson/pom.xml
  httpclient/pom.xml
  hystrix/pom.xml
  jackson-jaxb/pom.xml
  jackson/pom.xml
  java11/pom.xml
  java8/pom.xml
  jaxb/pom.xml
  jaxrs/pom.xml
  jaxrs2/pom.xml
  okhttp/pom.xml
  pom.xml
  reactive/pom.xml
  ribbon/pom.xml
  sax/pom.xml
  slf4j/pom.xml
  src/config/pomSortOrder.xml
Labels: enhancement, hacktoberfest

#737 Unwrap RetryableException and throw cause
  README.md
  core/src/main/java/feign/ExceptionPropagationPolicy.java
  core/src/main/java/feign/Feign.java
  core/src/main/java/feign/ReflectiveFeign.java
  core/src/main/java/feign/SynchronousMethodHandler.java
  core/src/test/java/feign/FeignTest.java
Labels: enhancement, waiting for feedback

#821 NPE when resolving a template with binary body
  core/src/main/java/feign/Request.java
  core/src/main/java/feign/RequestTemplate.java
  core/src/test/java/feign/RequestTemplateTest.java
  jaxb/src/test/java/feign/jaxb/examples/AWSSignatureVersion4.java
  mock/src/main/java/feign/mock/MockClient.java
  mock/src/test/java/feign/mock/MockClientSequentialTest.java
  ribbon/src/test/java/feign/ribbon/LBClientTest.java
  sax/src/test/java/feign/sax/examples/AWSSignatureVersion4.java
Labels: bug, ready to merge, regression, waiting for votes

#824 support PATCH with empty body paramter.
  CHANGELOG.md
  core/src/test/java/feign/client/AbstractClientTest.java
  core/src/test/java/feign/client/DefaultClientTest.java
  java11/src/test/java/feign/httpclient/test/Http2ClientTest.java
  jaxrs2/src/test/java/feign/jaxrs2/JAXRSClientTest.java
  okhttp/src/main/java/feign/okhttp/OkHttpClient.java
Labels: enhancement, ready to merge
