Repository OpenFeign/feign, pull requests merged in 2018-08, with the labels that each got.

#707 Build feign with java 11
  .mvn/wrapper/maven-wrapper.properties
  .travis.yml
  CHANGELOG.md
  jackson-jaxb/pom.xml
  jackson/src/main/java/feign/jackson/JacksonIteratorDecoder.java
  jaxb/pom.xml
  pom.xml
Labels: enhancement

#758 Allow decoding of parameterizedTypes (generics) Fixes #759
  jaxb/src/main/java/feign/jaxb/JAXBDecoder.java
  jaxb/src/test/java/feign/jaxb/JAXBCodecTest.java
Labels: bug

#766 support charset when build Reader for Response.Body
  core/src/main/java/feign/Response.java
  core/src/test/java/feign/FeignBuilderTest.java
  httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java
  okhttp/src/main/java/feign/okhttp/OkHttpClient.java
Labels: enhancement, waiting for feedback

#765 Adding Multiple Values for Consumes and Produces
  core/src/main/java/feign/Util.java
  core/src/test/java/feign/UtilTest.java
  jaxrs/README.md
  jaxrs/src/main/java/feign/jaxrs/JAXRSContract.java
  jaxrs/src/test/java/feign/jaxrs/JAXRSContractTest.java
Labels: enhancement, waiting for votes

#769 Added FeignRequestException, FeignResponseException
  core/src/main/java/feign/FeignException.java
  core/src/test/java/feign/FeignTest.java
  core/src/test/java/feign/client/AbstractClientTest.java
  core/src/test/java/feign/codec/DefaultErrorDecoderTest.java
Labels: enhancement
