Repository OpenFeign/feign, pull requests merged in 2019-08, with the labels that each got.

#1022 Fix Response.InputStreamBody missing toString implementation
  core/src/main/java/feign/Response.java
Labels: ready to merge

#1039 Request field added to FeignException
  core/src/main/java/feign/FeignException.java
  core/src/main/java/feign/Response.java
  core/src/main/java/feign/RetryableException.java
  core/src/main/java/feign/SynchronousMethodHandler.java
  core/src/main/java/feign/codec/DecodeException.java
  core/src/main/java/feign/codec/ErrorDecoder.java
  core/src/main/java/feign/codec/StringDecoder.java
  core/src/test/java/feign/FeignExceptionTest.java
  core/src/test/java/feign/FeignTest.java
  core/src/test/java/feign/RequestTemplateTest.java
  core/src/test/java/feign/RetryerTest.java
  core/src/test/java/feign/codec/RetryAfterDecoderTest.java
  core/src/test/java/feign/template/HeaderTemplateTest.java
  jackson/src/main/java/feign/jackson/JacksonIteratorDecoder.java
  jaxb/src/main/java/feign/jaxb/JAXBDecoder.java
  reactive/src/main/java/feign/reactive/ReactiveInvocationHandler.java
  reactive/src/test/java/feign/reactive/ReactiveFeignIntegrationTest.java
  reactive/src/test/java/feign/reactive/ReactiveInvocationHandlerTest.java
  sax/src/main/java/feign/sax/SAXDecoder.java
  soap/src/main/java/feign/soap/SOAPDecoder.java
Labels: ready to merge

#1054 Add Roadmap to Readme
  README.md
Labels: documentation

#1056 GH-1021: Add Request Line override documentation
  README.md
Labels: documentation

#1055 GH-1023: Correct Reactive Examples
  reactive/README.md
Labels: documentation

#1047 Unexpected JavaLogger behavior fixed
  README.md
  core/src/main/java/feign/Logger.java
  core/src/test/java/feign/MultipleLoggerTest.java
Labels: feedback provided, ready to merge

#1057 Add Google HTTP Client support
  googlehttpclient/README.md
  googlehttpclient/pom.xml
  googlehttpclient/src/main/java/feign/googlehttpclient/GoogleHttpClient.java
  googlehttpclient/src/test/java/feign/googlehttpclient/GoogleHttpClientTest.java
  pom.xml
Labels: enhancement, ready to merge
