Repository OpenFeign/feign, pull requests merged in 2019-10, with the labels that each got.

#1086 Remove java8 module
  java8/pom.xml
  pom.xml
Labels: ready to merge

#1090 Add composed Spring annotations support
  spring4/README.md
  spring4/src/main/java/feign/spring/SpringContract.java
  spring4/src/test/java/feign/spring/SpringContractTest.java
Labels: enhancement, ready to merge

#1095 1048 simple illustration - more details in the default feignexception…
  core/src/main/java/feign/FeignException.java
  core/src/test/java/feign/client/AbstractClientTest.java
  core/src/test/java/feign/codec/DefaultErrorDecoderHttpErrorTest.java
  core/src/test/java/feign/codec/DefaultErrorDecoderTest.java
  hystrix/src/test/java/feign/hystrix/FallbackFactoryTest.java
  soap/src/test/java/feign/soap/SOAPFaultDecoderTest.java
Labels: enhancement, feedback provided, ready to merge

#1098 Fixes a typo in Contract.java method
  benchmark/src/main/java/feign/benchmark/WhatShouldWeCacheBenchmarks.java
  core/src/main/java/feign/Contract.java
  core/src/main/java/feign/DeclarativeContract.java
  core/src/main/java/feign/ReflectiveFeign.java
  core/src/test/java/feign/ContractWithRuntimeInjectionTest.java
  core/src/test/java/feign/DefaultContractTest.java
  hystrix/src/main/java/feign/hystrix/HystrixDelegatingContract.java
  reactive/src/main/java/feign/reactive/ReactiveDelegatingContract.java
  reactive/src/test/java/feign/reactive/ReactiveDelegatingContractTest.java
Labels: ready to merge
