Repository OpenFeign/feign, pull requests merged in 2019-02, with the labels that each got.

#882 Adding URI segment specific encoding
  README.md
  core/src/main/java/feign/template/Expressions.java
  core/src/main/java/feign/template/Template.java
  core/src/main/java/feign/template/UriUtils.java
  core/src/test/java/feign/FeignTest.java
  core/src/test/java/feign/template/UriTemplateTest.java
  core/src/test/java/feign/template/UriUtilsTest.java
  java11/src/test/java/feign/http2client/test/Http2ClientTest.java
Labels: bug, ready to merge, regression

#880 Make status mandatory
  core/src/main/java/feign/FeignException.java
  core/src/main/java/feign/RetryableException.java
  core/src/main/java/feign/SynchronousMethodHandler.java
  core/src/main/java/feign/codec/DecodeException.java
  core/src/main/java/feign/codec/EncodeException.java
  core/src/main/java/feign/codec/ErrorDecoder.java
  core/src/main/java/feign/codec/StringDecoder.java
  core/src/test/java/feign/FeignTest.java
  core/src/test/java/feign/RetryerTest.java
  jackson/src/main/java/feign/jackson/JacksonIteratorDecoder.java
  jaxb/src/main/java/feign/jaxb/JAXBDecoder.java
  sax/src/main/java/feign/sax/SAXDecoder.java
  soap/src/main/java/feign/soap/SOAPDecoder.java
Labels: ready to merge

#886 Updating Hystrix Versions
  hystrix/pom.xml
  pom.xml
Labels: ready to merge, security

#871 Allow 1xx status codes
  core/src/main/java/feign/Response.java
  core/src/test/java/feign/ResponseTest.java
Labels: bug, ready to merge
