Repository OpenFeign/feign, pull requests merged in 2019-07, with the labels that each got.

#999 Avoided url appending with slash when matrix parameter exists
  core/src/main/java/feign/RequestTemplate.java
  core/src/test/java/feign/RequestTemplateTest.java
Labels: ready to merge

#1004 Fixes 1003: Do not wrap exceptions in RuntimeException
  reactive/pom.xml
  reactive/src/main/java/feign/reactive/ReactiveInvocationHandler.java
  reactive/src/main/java/feign/reactive/ReactorInvocationHandler.java
  reactive/src/main/java/feign/reactive/RxJavaInvocationHandler.java
  reactive/src/test/java/feign/reactive/ReactiveFeignIntegrationTest.java
  reactive/src/test/java/feign/reactive/ReactiveInvocationHandlerTest.java
Labels: ready to merge

#1012 Respect decode404 flag and decode 404 response body
  gson/src/main/java/feign/gson/GsonDecoder.java
  gson/src/test/java/feign/gson/GsonCodecTest.java
  jackson-jaxb/src/main/java/feign/jackson/jaxb/JacksonJaxbJsonDecoder.java
  jackson-jaxb/src/test/java/feign/jackson/jaxb/JacksonJaxbCodecTest.java
  jackson/src/main/java/feign/jackson/JacksonDecoder.java
  jackson/src/main/java/feign/jackson/JacksonIteratorDecoder.java
  jackson/src/test/java/feign/jackson/JacksonCodecTest.java
  jaxb/src/main/java/feign/jaxb/JAXBDecoder.java
  jaxb/src/test/java/feign/jaxb/JAXBCodecTest.java
  sax/src/main/java/feign/sax/SAXDecoder.java
  sax/src/test/java/feign/sax/SAXDecoderTest.java
  soap/src/test/java/feign/soap/SOAPCodecTest.java
Labels: feedback provided

#1009 Maintain user-given order for header values
  core/src/main/java/feign/template/HeaderTemplate.java
  core/src/test/java/feign/template/HeaderTemplateTest.java
  jaxrs/src/test/java/feign/jaxrs/JAXRSContractTest.java
Labels: bug, ready to merge
