Repository OpenFeign/feign, pull requests merged in 2019-03, with the labels that each got.

#910 Updated Query Expressions to support empty and undefined values
  README.md
  core/src/main/java/feign/template/QueryTemplate.java
  core/src/main/java/feign/template/Template.java
  core/src/test/java/feign/template/QueryTemplateTest.java
  jaxb/pom.xml
Labels: regression

#914 Fixes NullPointerException when accessing a FeignException's content
  core/src/main/java/feign/FeignException.java
  core/src/test/java/feign/FeignTest.java
Labels: bug

#909 Removed Duplicate Expansion
  core/src/main/java/feign/RequestTemplate.java
Labels: bug

#921 Update README.md
  README.md
Labels: needs info
