Repository OpenFeign/feign, pull requests merged in 2019-05, with the labels that each got.

#958 Feature/template unit test
  core/src/main/java/feign/Client.java
  core/src/main/java/feign/Retryer.java
  core/src/test/java/feign/template/HeaderTemplateTest.java
Labels: ready to merge, waiting for feedback

#959 Feature/replace deprecated body
  core/src/main/java/feign/Client.java
  core/src/main/java/feign/FeignException.java
  core/src/main/java/feign/Logger.java
  core/src/test/java/feign/TargetTest.java
  httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java
  java11/src/main/java/feign/http2client/Http2Client.java
  jaxrs2/src/main/java/feign/jaxrs2/JAXRSClient.java
  mock/src/main/java/feign/mock/RequestKey.java
  mock/src/test/java/feign/mock/MockClientTest.java
  okhttp/src/main/java/feign/okhttp/OkHttpClient.java
  ribbon/src/main/java/feign/ribbon/LBClient.java
Labels: chore, ready to merge

#964 Add test scope to java-hamcrest dependency
  jaxrs2/pom.xml
Labels: ready to merge

#962 Initial CI Build Refactor
  .travis.yml
  RELEASE.md
  pom.xml
  travis/release.sh
  travis/settings.xml
Labels: chore

#953 Testing feign-example-github jar
  .travis.yml
  example-github/pom.xml
  example-github/src/main/java/example/github/GitHubExample.java
  example-github/src/test/java/feign/example/github/GitHubExampleIT.java
  example-wikipedia/pom.xml
  example-wikipedia/src/main/java/example/wikipedia/ResponseAdapter.java
  example-wikipedia/src/main/java/example/wikipedia/WikipediaExample.java
  example-wikipedia/src/test/java/feign/example/wikipedia/WikipediaExampleIT.java
Labels: chore, ready to merge

#938 simplify valuesOrEmpty
  core/src/main/java/feign/Util.java
Labels: chore, ready to merge

#960 This pr resolves QueryMap inheritance issue #927
  core/src/main/java/feign/querymap/FieldQueryMapEncoder.java
  core/src/test/java/feign/ChildPojo.java
  core/src/test/java/feign/FeignTest.java
Labels: bug, ready to merge

#980 Parse Retry-After header responses that include decimal points
  core/src/main/java/feign/codec/ErrorDecoder.java
  core/src/test/java/feign/codec/RetryAfterDecoderTest.java
Labels: enhancement

#968 Migrating to Sonatype OSSRH from JCenter
  .travis.yml
  mvnw.cmd
  pom.xml
  src/config/bom.xml
  travis/codesigning.asc.enc
  travis/settings.xml
  travis/sign.sh
Labels: ready to merge

#854 Fine-grained HTTP error exceptions with client and server errors
  core/src/main/java/feign/FeignException.java
  core/src/test/java/feign/codec/DefaultErrorDecoderHttpErrorTest.java
Labels: enhancement, ready to merge

#970 Adds support for per request timeout options. Fixes #562
  core/src/main/java/feign/Contract.java
  core/src/main/java/feign/SynchronousMethodHandler.java
  core/src/test/java/feign/OptionsTest.java
Labels: enhancement, ready to merge
