Repository OpenFeign/feign, pull requests merged in 2019-12, with the labels that each got.

#1130 Force followRedirects on the OkHttpClient when needed
  okhttp/src/main/java/feign/okhttp/OkHttpClient.java
  okhttp/src/test/java/feign/okhttp/OkHttpClientTest.java
Labels: bug, feedback provided

#1140 Ensure all brackets are decoded in JSON based Body Templates
  core/src/main/java/feign/template/BodyTemplate.java
  core/src/test/java/feign/template/BodyTemplateTest.java
Labels: bug

#1139 Remove Template Expression naming restrictions
  core/src/main/java/feign/template/Expressions.java
  core/src/test/java/feign/template/QueryTemplateTest.java
Labels: bug

#1144 Include variables Query Parameter Names when listing template parameters
  core/src/main/java/feign/template/QueryTemplate.java
Labels: bug

#1146 Adds logging level to documentation. Fixes #1142
  README.md
  slf4j/README.md
Labels: documentation

#1137 fix inconsistent bug
  core/src/main/java/feign/Contract.java
  core/src/test/java/feign/DefaultContractTest.java
Labels: ready to merge

#1147 Update documentation regarding decodeSlash
  README.md
Labels: documentation

#1148 Clarify when to use a custom Target or Request Interceptor
  README.md
Labels: documentation
