Repository OpenFeign/feign, pull requests merged in 2020-12, with the labels that each got.

#1309 Allows @Param value in default contract to be taken from param names.
  README.md
  core/src/main/java/feign/Contract.java
  core/src/main/java/feign/Param.java
  core/src/test/java/feign/DefaultContractTest.java
  pom.xml
Labels: documentation, feedback provided, ready to merge

#1307 Java11client connect timeout
  java11/src/main/java/feign/http2client/Http2Client.java
Labels: feedback provided, ready to merge

#1311 Support metric names customization
  micrometer/src/main/java/feign/micrometer/FeignMetricName.java
  micrometer/src/main/java/feign/micrometer/MeteredClient.java
  micrometer/src/main/java/feign/micrometer/MeteredDecoder.java
  micrometer/src/main/java/feign/micrometer/MeteredEncoder.java
  micrometer/src/main/java/feign/micrometer/MeteredInvocationHandleFactory.java
  micrometer/src/main/java/feign/micrometer/MetricName.java
Labels: feedback provided, ready to merge

#1294 Ignore @BeanParam
  jaxrs2/src/main/java/feign/jaxrs2/JAXRS2Contract.java
  jaxrs2/src/test/java/feign/jaxrs2/JAXRS2ContractTest.java
Labels: hacktoberfest, hacktoberfest-accepted, ready to merge

#1351 connection request timeout setting documentation. For #1318
  README.md
  example-github/src/main/java/example/github/GitHubExample.java
  example-wikipedia/src/main/java/example/wikipedia/WikipediaExample.java
Labels: documentation, ready to merge
