Repository OpenFeign/feign, pull requests merged in 2020-01, with the labels that each got.

#1145 Remove deprecated code usage from core module
  benchmark/src/main/java/feign/benchmark/DecoderIteratorsBenchmark.java
  core/src/main/java/feign/Client.java
  core/src/main/java/feign/Contract.java
  core/src/main/java/feign/Feign.java
  core/src/main/java/feign/FeignException.java
  core/src/main/java/feign/Logger.java
  core/src/main/java/feign/QueryMap.java
  core/src/main/java/feign/Request.java
  core/src/main/java/feign/RequestTemplate.java
  core/src/main/java/feign/Response.java
  core/src/main/java/feign/codec/StringDecoder.java
  core/src/main/java/feign/template/BodyTemplate.java
  core/src/test/java/feign/DefaultContractTest.java
  core/src/test/java/feign/DefaultQueryMapEncoderTest.java
  core/src/test/java/feign/FeignBuilderTest.java
  core/src/test/java/feign/FeignTest.java
  core/src/test/java/feign/LoggerTest.java
  core/src/test/java/feign/MethodMetadataPresenceTest.java
  core/src/test/java/feign/MultipleLoggerTest.java
  core/src/test/java/feign/OptionsTest.java
  core/src/test/java/feign/RequestTemplateTest.java
  core/src/test/java/feign/ResponseTest.java
  core/src/test/java/feign/RetryerTest.java
  core/src/test/java/feign/TargetTest.java
  core/src/test/java/feign/assertj/RequestTemplateAssert.java
  core/src/test/java/feign/client/AbstractClientTest.java
  core/src/test/java/feign/codec/DefaultDecoderTest.java
  core/src/test/java/feign/codec/DefaultErrorDecoderHttpErrorTest.java
  core/src/test/java/feign/codec/DefaultErrorDecoderTest.java
  core/src/test/java/feign/examples/GitHubExample.java
  core/src/test/java/feign/stream/StreamDecoderTest.java
  googlehttpclient/src/main/java/feign/googlehttpclient/GoogleHttpClient.java
  gson/src/main/java/feign/gson/GsonDecoder.java
  gson/src/test/java/feign/gson/GsonCodecTest.java
  hc5/src/main/java/feign/hc5/ApacheHttp5Client.java
  httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java
  jackson-jaxb/src/test/java/feign/jackson/jaxb/JacksonJaxbCodecTest.java
  jackson/src/main/java/feign/jackson/JacksonDecoder.java
  jackson/src/main/java/feign/jackson/JacksonIteratorDecoder.java
  jackson/src/test/java/feign/jackson/JacksonCodecTest.java
  jackson/src/test/java/feign/jackson/JacksonIteratorTest.java
  java11/src/main/java/feign/http2client/Http2Client.java
  jaxb/src/test/java/feign/jaxb/JAXBCodecTest.java
  jaxb/src/test/java/feign/jaxb/examples/AWSSignatureVersion4.java
  jaxrs2/src/main/java/feign/jaxrs2/JAXRSClient.java
  jaxrs2/src/test/java/feign/jaxrs2/JAXRSClientTest.java
  mock/src/main/java/feign/mock/RequestKey.java
  mock/src/test/java/feign/mock/MockClientTest.java
  mock/src/test/java/feign/mock/RequestKeyTest.java
  okhttp/src/main/java/feign/okhttp/OkHttpClient.java
  okhttp/src/test/java/feign/okhttp/OkHttpClientTest.java
  ribbon/src/main/java/feign/ribbon/LBClient.java
  ribbon/src/test/java/feign/ribbon/LBClientTest.java
  ribbon/src/test/java/feign/ribbon/RibbonClientTest.java
  sax/src/test/java/feign/sax/SAXDecoderTest.java
  sax/src/test/java/feign/sax/examples/AWSSignatureVersion4.java
  slf4j/src/test/java/feign/slf4j/Slf4jLoggerTest.java
  soap/src/test/java/feign/soap/SOAPCodecTest.java
  soap/src/test/java/feign/soap/SOAPFaultDecoderTest.java
  spring4/src/main/java/feign/spring/SpringContract.java
Labels: regression

#1158 Update okhttp client version from 3.6.0 to 3.14.4.
  pom.xml
Labels: ready to merge

#1160 Correct Encoding and restore decodeSlash in QueryTemplate
  README.md
  benchmark/src/main/java/feign/benchmark/RealRequestBenchmarks.java
  core/src/main/java/feign/Client.java
  core/src/main/java/feign/CollectionFormat.java
  core/src/main/java/feign/RequestTemplate.java
  core/src/main/java/feign/Types.java
  core/src/main/java/feign/Util.java
  core/src/main/java/feign/stream/StreamDecoder.java
  core/src/main/java/feign/template/Expression.java
  core/src/main/java/feign/template/QueryTemplate.java
  core/src/main/java/feign/template/UriUtils.java
  core/src/test/java/feign/RequestTemplateTest.java
  core/src/test/java/feign/TargetTest.java
  core/src/test/java/feign/assertj/RecordedRequestAssert.java
  core/src/test/java/feign/codec/DefaultErrorDecoderTest.java
  core/src/test/java/feign/stream/StreamDecoderTest.java
  core/src/test/java/feign/template/QueryTemplateTest.java
  core/src/test/java/feign/template/UriTemplateTest.java
  googlehttpclient/src/main/java/feign/googlehttpclient/GoogleHttpClient.java
  gson/src/main/java/feign/gson/GsonDecoder.java
  gson/src/test/java/feign/gson/GsonCodecTest.java
  hc5/src/main/java/feign/hc5/ApacheHttp5Client.java
  httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java
  httpclient/src/test/java/feign/httpclient/ApacheHttpClientTest.java
  jackson-jaxb/src/main/java/feign/jackson/jaxb/JacksonJaxbJsonDecoder.java
  jackson/src/test/java/feign/jackson/JacksonCodecTest.java
  jaxrs/src/test/java/feign/jaxrs/JAXRSContractTest.java
  reactive/src/main/java/feign/reactive/ReactiveFeign.java
  ribbon/src/main/java/feign/ribbon/LBClient.java
  sax/src/main/java/feign/sax/SAXDecoder.java
  soap/src/test/java/feign/soap/SOAPCodecTest.java
  spring4/src/test/java/feign/spring/SpringContractTest.java
Labels: bug

#1141 Add support for SOAP Envelope declarations to be inherited
  soap/src/main/java/feign/soap/SOAPDecoder.java
  soap/src/test/java/feign/soap/SOAPCodecTest.java
  soap/src/test/java/feign/soap/package-info.java
Labels: bug, ready to merge

#1164 Restore Request.Body accessibility for compatibility
  core/src/main/java/feign/Request.java
  core/src/main/java/feign/RequestTemplate.java
  core/src/test/java/feign/client/AbstractClientTest.java
  hc5/src/test/java/feign/hc5/ApacheHttp5ClientTest.java
  pom.xml
Labels: breaking change, bug

#1165 Use LinkedHashMap for deterministic iterations
  mock/src/main/java/feign/mock/RequestHeaders.java
  mock/src/test/java/feign/mock/RequestHeadersTest.java
Labels: enhancement, feedback provided, ready to merge, waiting for feedback
