Repository OpenFeign/feign, pull requests merged in 2020-03, with the labels that each got.

#1184 Overriding query parameter name
  core/src/main/java/feign/Param.java
  core/src/main/java/feign/querymap/BeanQueryMapEncoder.java
  core/src/main/java/feign/querymap/FieldQueryMapEncoder.java
  core/src/test/java/feign/querymap/BeanQueryMapEncoderTest.java
  core/src/test/java/feign/querymap/FieldQueryMapEncoderTest.java
Labels: feedback provided

#1176 Add extra information when failing to parse contract
  core/src/main/java/feign/Contract.java
  core/src/main/java/feign/DeclarativeContract.java
  core/src/main/java/feign/MethodMetadata.java
  core/src/test/java/feign/DefaultContractTest.java
Labels: chore

#1181 Metric API
  core/src/main/java/feign/Capability.java
  core/src/main/java/feign/Feign.java
  core/src/test/java/feign/CapabilityTest.java
  hystrix/src/main/java/feign/hystrix/HystrixCapability.java
  hystrix/src/test/java/feign/hystrix/HystrixBuilderTest.java
  hystrix/src/test/java/feign/hystrix/HystrixCapabilityTest.java
  metrics5/pom.xml
  metrics5/src/main/java/feign/metrics5/CountingInputStream.java
  metrics5/src/main/java/feign/metrics5/FeignMetricName.java
  metrics5/src/main/java/feign/metrics5/MeteredBody.java
  metrics5/src/main/java/feign/metrics5/MeteredClient.java
  metrics5/src/main/java/feign/metrics5/MeteredDecoder.java
  metrics5/src/main/java/feign/metrics5/MeteredEncoder.java
  metrics5/src/main/java/feign/metrics5/MeteredInvocationHandleFactory.java
  metrics5/src/main/java/feign/metrics5/MetricSuppliers.java
  metrics5/src/main/java/feign/metrics5/Metrics5Capability.java
  metrics5/src/test/java/feign/metrics5/Metrics5CapabilityTest.java
  pom.xml
Labels: enhancement, ready to merge
