Repository OpenFeign/feign, pull requests merged in 2021-07, with the labels that each got.

#1454 import annotation error decoder
  annotation-error-decoder/README.md
  annotation-error-decoder/pom.xml
  annotation-error-decoder/src/main/java/feign/error/AnnotationErrorDecoder.java
  annotation-error-decoder/src/main/java/feign/error/ErrorCodes.java
  annotation-error-decoder/src/main/java/feign/error/ErrorHandling.java
  annotation-error-decoder/src/main/java/feign/error/ExceptionGenerator.java
  annotation-error-decoder/src/main/java/feign/error/FeignExceptionConstructor.java
  annotation-error-decoder/src/main/java/feign/error/MethodErrorHandler.java
  annotation-error-decoder/src/main/java/feign/error/ResponseBody.java
  annotation-error-decoder/src/main/java/feign/error/ResponseHeaders.java
  annotation-error-decoder/src/test/java/feign/error/AbstractAnnotationErrorDecoderTest.java
  annotation-error-decoder/src/test/java/feign/error/AnnotationErrorDecoderClassInheritanceTest.java
  annotation-error-decoder/src/test/java/feign/error/AnnotationErrorDecoderExceptionConstructorsTest.java
  annotation-error-decoder/src/test/java/feign/error/AnnotationErrorDecoderIllegalInterfacesTest.java
  annotation-error-decoder/src/test/java/feign/error/AnnotationErrorDecoderInheritanceTest.java
  annotation-error-decoder/src/test/java/feign/error/AnnotationErrorDecoderNoAnnotationTest.java
  annotation-error-decoder/src/test/java/feign/error/AnnotationErrorDecoderPriorityTest.java
  annotation-error-decoder/src/test/java/feign/error/TestPojo.java
  pom.xml
  src/docs/overview-mindmap.iuml
Labels: enhancement, ready to merge, waiting for votes

#1452 Add response headers to FeignException
  core/pom.xml
  core/src/main/java/feign/FeignException.java
  core/src/main/java/feign/Response.java
  core/src/main/java/feign/Util.java
  core/src/test/java/feign/AsyncFeignTest.java
  core/src/test/java/feign/FeignBuilderTest.java
  core/src/test/java/feign/FeignExceptionTest.java
  core/src/test/java/feign/FeignTest.java
  core/src/test/java/feign/FeignUnderAsyncTest.java
  core/src/test/java/feign/ResponseTest.java
  core/src/test/java/feign/UtilTest.java
  core/src/test/java/feign/client/AbstractClientTest.java
  hc5/src/test/java/feign/hc5/AsyncApacheHttp5ClientTest.java
  jaxrs2/src/test/java/feign/jaxrs2/JAXRSClientTest.java
  micrometer/src/test/java/feign/micrometer/AbstractMetricsTestBase.java
Labels: feedback provided, waiting for votes

#1459 Modifying Contract to support passing all parameters to encoders #1448
  core/src/main/java/feign/AlwaysEncodeBodyContract.java
  core/src/main/java/feign/Contract.java
  core/src/main/java/feign/DeclarativeContract.java
  core/src/main/java/feign/MethodMetadata.java
  core/src/main/java/feign/ReflectiveFeign.java
  core/src/test/java/feign/AlwaysEncodeBodyContractTest.java
Labels: feedback provided
