Repository OpenFeign/feign, pull requests merged in 2022-06, with the labels that each got.

#1287 Fix for #1286
  hc5/src/main/java/feign/hc5/ApacheHttp5Client.java
  hc5/src/main/java/feign/hc5/AsyncApacheHttp5Client.java
  httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java
Labels: bug, waiting for feedback, hacktoberfest, hacktoberfest-accepted

#1626 Support of capabilities for AsyncFeign
  core/pom.xml
  core/src/main/java/feign/AsyncContextSupplier.java
  core/src/main/java/feign/AsyncFeign.java
  core/src/main/java/feign/BaseBuilder.java
  core/src/main/java/feign/Capability.java
  core/src/main/java/feign/Feign.java
  core/src/main/java/feign/ReflectiveAsyncFeign.java
  core/src/main/java/feign/Util.java
  core/src/test/java/feign/BaseBuilderTest.java
  core/src/test/java/feign/CapabilityTest.java
  dropwizard-metrics4/pom.xml
  dropwizard-metrics4/src/main/java/feign/metrics4/BaseMeteredClient.java
  dropwizard-metrics4/src/main/java/feign/metrics4/MeteredAsyncClient.java
  dropwizard-metrics4/src/main/java/feign/metrics4/MeteredClient.java
  dropwizard-metrics4/src/main/java/feign/metrics4/Metrics4Capability.java
  dropwizard-metrics4/src/test/java/feign/metrics4/Metrics4CapabilityTest.java
  dropwizard-metrics5/src/main/java/feign/metrics5/BaseMeteredClient.java
  dropwizard-metrics5/src/main/java/feign/metrics5/FeignMetricName.java
  dropwizard-metrics5/src/main/java/feign/metrics5/MeteredAsyncClient.java
  dropwizard-metrics5/src/main/java/feign/metrics5/MeteredClient.java
  dropwizard-metrics5/src/main/java/feign/metrics5/Metrics5Capability.java
  dropwizard-metrics5/src/test/java/feign/metrics5/Metrics5CapabilityTest.java
  micrometer/src/main/java/feign/micrometer/BaseMeteredClient.java
  micrometer/src/main/java/feign/micrometer/MeteredAsyncClient.java
  micrometer/src/main/java/feign/micrometer/MeteredClient.java
  micrometer/src/main/java/feign/micrometer/MicrometerCapability.java
  micrometer/src/test/java/feign/micrometer/AbstractMetricsTestBase.java
  micrometer/src/test/java/feign/micrometer/MicrometerCapabilityTest.java
  mock/src/main/java/feign/mock/MockClient.java
Labels: waiting for feedback, waiting for votes, ready to merge, feedback provided

#1634 Alternative ResponseInterceptor attempt
  core/src/main/java/feign/AsyncFeign.java
  core/src/main/java/feign/AsyncResponseHandler.java
  core/src/main/java/feign/BaseBuilder.java
  core/src/main/java/feign/Capability.java
  core/src/main/java/feign/Feign.java
  core/src/main/java/feign/InvocationContext.java
  core/src/main/java/feign/ResponseInterceptor.java
  core/src/main/java/feign/SynchronousMethodHandler.java
  core/src/test/java/feign/AsyncFeignTest.java
  core/src/test/java/feign/BaseBuilderTest.java
Labels: ready to merge
